fix: fixes EOF error when having HTTP POST requests
ExpediaGroup/mittens pull request #342
Opened 2024-01-17 10:19 UTC by jrauschenbusch

Mittens requests are recycled within the requests channel. Once the body i/o reader was closed, succeeding requests were not successful.

### :pencil: Description

Currently mittens is broken due to an bug introduced in v1.46. During the processing of requests an i/o reader is passed to the client which leads to EOF errors on server side when the same request body is read the 2nd time. Hence only the first request of a warm-up succeeds and all others fail.  This should only affect configurations using POST data, but this needs to be fixed.

### :link: Related Issues

2024-01-17 10:19 UTC, jrauschenbusch commented on internal/pkg/http/client.go
> +	var body io.Reader
Re-introducing the i/o reader per request

2024-01-17 10:20 UTC, jrauschenbusch commented on internal/pkg/http/client.go
> +	if req.Body != nil {
Body must be closed when there is no error and when a body is present. In case of GET there is no Body.

2024-01-17 10:21 UTC, jrauschenbusch commented on internal/pkg/http/utils.go
> -	pr, pw := io.Pipe()
Optimization not required as mittens requests are re-used in the channel. So compression is only done once for each request element.

2024-01-17 10:22 UTC, jrauschenbusch commented on test/root_test.go
> +func TestCompressWithGZip(t *testing.T) {
e2e test for compression support

2024-01-17 10:25 UTC, jrauschenbusch commented
@nikos912000 Sorry for having to fix this directly after the release of v1.46. Unfortunately all existing tests were not able to detect an issue within the request processing. I tried to add a useful test here, but maybe there should be another one.

2024-01-19 08:31 UTC, jrauschenbusch commented
@nikos912000 @worldtiki Review required

2024-01-19 08:32 UTC, jrauschenbusch commented on internal/pkg/http/utils.go
> +func compressGzip(data []byte) (io.Reader, error) {
Aligned implementation of all compression functions

2024-01-19 13:55 UTC, worldtiki approved these changes

2024-01-19 14:38 UTC, nikos912000 commented
Thanks for this.
Something looks wrong with the flags in the tests, these are no more passed - I don't think it was this PR that caused it.
A bit busy to debug properly but I will try find some time and let our teams know.
Let's not merge until we fix this please.

2024-01-19 14:42 UTC, nikos912000 requested changes
Thanks for this.
Something looks wrong with the flags in the tests, these are no more passed - I don't think it was this PR that caused it.
A bit busy to debug properly atm but I will try find some time and let our teams know.

2024-02-02 20:56 UTC, nikos912000 commented
I debugged this and recalled that we identified this issue in the past. It has to do with the fact that the command line arguments are [parsed](https://github.com/ExpediaGroup/mittens/blob/6b70df152135c2d64a1cf26c7547f9d92cf804a4/cmd/root.go#L35) after setting their [default values](https://github.com/ExpediaGroup/mittens/blob/6b70df152135c2d64a1cf26c7547f9d92cf804a4/cmd/flags/target.go#L58). 

For instance, the `HTTPPort` will be `8080` at [this](https://github.com/ExpediaGroup/mittens/blob/6b70df152135c2d64a1cf26c7547f9d92cf804a4/cmd/flags/target.go#L49) point and the `ReadinessPort` will be set to its default value, which is `8080` [here](https://github.com/ExpediaGroup/mittens/blob/6b70df152135c2d64a1cf26c7547f9d92cf804a4/cmd/flags/target.go#L58), too.
Finally, the cmd args will be parsed at [this](https://github.com/ExpediaGroup/mittens/blob/6b70df152135c2d64a1cf26c7547f9d92cf804a4/cmd/root.go#L35) point setting _only_ the `HTTPPort` to the passed value.

As this does not have to do with this PR, happy to merge it.

2024-02-03 07:57 UTC, jrauschenbusch commented
I tested it now in our pre-production and afterwards production. Works like a charm. HTTP/2 and stream compression.

2024-02-03 09:49 UTC, nikos912000 approved these changes

2024-02-03 09:50 UTC, merged

2024-02-14 18:48 UTC, sumitanvekar commented
@jrauschenbusch thank you for contribution. this is now released in https://github.com/ExpediaGroup/mittens/releases/tag/1.47.0